In [7]:
import math

def basic_sigmoid(x):

    s= 1/(1+ math.exp(-x))
    
    return s


In [8]:
basic_sigmoid(3)

0.9525741268224334

In [9]:
x=[1,2,3]

In [10]:
import numpy as np


In [13]:
y=np.array([1,2,3])

print(np.exp(y))

[  2.71828183   7.3890561   20.08553692]


In [14]:
print(y+3)

[4 5 6]


### 1.2 - Sigmoid gradient

As you've seen in lecture, you will need to compute gradients to optimize loss functions using backpropagation. Let's code your first gradient function.

**Exercise**: Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is: $$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$
You often code this function in two steps:
1. Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
2. Compute $\sigma'(x) = s(1-s)$

In [15]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])


In [17]:
image.shape

(3, 3, 2)

In [30]:
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    v = image.reshape((image.shape[0]*image.shape[1],image.shape[2]))
    ### END CODE HERE ###
    
    return v

In [31]:
print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[ 0.67826139  0.29380381]
 [ 0.90714982  0.52835647]
 [ 0.4215251   0.45017551]
 [ 0.92814219  0.96677647]
 [ 0.85304703  0.52351845]
 [ 0.19981397  0.27417313]
 [ 0.60659855  0.00533165]
 [ 0.10820313  0.49978937]
 [ 0.34144279  0.94630077]]


In [20]:
image2vector(image).shape

(9, 2)

In [ ]:
z=np.array([0,3,4])

In [47]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [46]:
def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss =np.sum(np.abs(y-yhat))
    ### END CODE HERE ###
    
    return loss

In [49]:

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.dot(y-yhat,y-yhat)
    ### END CODE HERE ###
    
    return loss

In [50]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


In [56]:
w=np.zeros((2,1))
w.shape

(2, 1)

In [70]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = np.dot(a,b)

c.shape


(4, 2)

In [75]:
a = np.random.randn(3, 4) # a.shape = (2, 3)
b = np.random.randn(4, 1) # b.shape = (2, 1)
c = a.T + b
c.shape

(4, 3)

In [79]:
d=a+b.T
d


array([[ 0.91091006, -0.08619926, -0.35513169,  1.61273789],
       [-0.16707074, -0.13211502,  2.97692557,  1.32010333],
       [-0.28611296,  0.34785295,  0.45361584,  2.07909214]])

In [72]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [81]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c.shape

(3, 3)